from fpdf import FPDF


def generate_pdf_report(candidate, resume_score, assessment_score, final_score, decision):

    pdf = FPDF()
    pdf.add_page()

    # -----------------------------
    # HEADER
    # -----------------------------
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 12, "TalentScout AI", ln=True, align="C")

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, "Automated Candidate Evaluation Report", ln=True, align="C")

    pdf.ln(10)

    # -----------------------------
    # CANDIDATE DETAILS
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Candidate Information", ln=True)

    pdf.set_font("Arial", "", 12)

    pdf.cell(0, 8, f"Name: {candidate.get('name','N/A')}", ln=True)
    pdf.cell(0, 8, f"Email: {candidate.get('email','N/A')}", ln=True)
    pdf.cell(0, 8, f"Phone: {candidate.get('phone','N/A')}", ln=True)
    pdf.cell(0, 8, f"Role: {candidate.get('role','N/A')}", ln=True)
    pdf.cell(0, 8, f"Experience: {candidate.get('experience','N/A')} years", ln=True)
    pdf.cell(0, 8, f"Location: {candidate.get('location','N/A')}", ln=True)

    pdf.ln(8)

    # -----------------------------
    # TECH STACK
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Detected Tech Stack", ln=True)

    pdf.set_font("Arial", "", 12)

    skills = candidate.get("tech_stack", [])

    if skills:
        tech_line = ", ".join(skills)
    else:
        tech_line = "No technologies detected"

    pdf.multi_cell(0, 8, tech_line)

    pdf.ln(8)

    # -----------------------------
    # SCORE TABLE
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Evaluation Scores", ln=True)

    pdf.set_font("Arial", "B", 12)

    pdf.cell(70, 8, "Metric", border=1)
    pdf.cell(50, 8, "Score", border=1)
    pdf.ln()

    pdf.set_font("Arial", "", 12)

    pdf.cell(70, 8, "Resume Score", border=1)
    pdf.cell(50, 8, f"{resume_score}/100", border=1)
    pdf.ln()

    pdf.cell(70, 8, "Technical Assessment", border=1)
    pdf.cell(50, 8, f"{assessment_score}/100", border=1)
    pdf.ln()

    pdf.cell(70, 8, "Final Candidate Score", border=1)
    pdf.cell(50, 8, f"{round(final_score,2)}", border=1)
    pdf.ln()

    pdf.ln(10)

    # -----------------------------
    # HIRING DECISION
    # -----------------------------
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Hiring Recommendation", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Decision: {decision}", ln=True)

    pdf.ln(15)

    # -----------------------------
    # FOOTER
    # -----------------------------
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by TalentScout AI Hiring Assistant", align="C")

    file_path = "candidate_report.pdf"

    pdf.output(file_path)

    return file_path
